/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:25f28bd8-9cd1-45bf-96a2-dd7583c4a7bb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MeAPSkcDq",
    "aws_user_pools_web_client_id": "39bv7jnfmc8ef2eabbkn0qf0lp",
    "oauth": {
        "domain": "default-domain-enviro.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/",
        "redirectSignOut": "exp://127.0.0.1:19000/--/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
